# Generated by Django 4.2.7 on 2023-12-06 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='always_show',
            field=models.BooleanField(blank=True, default=False, help_text='【目录】只有一个子路由是否始终显示(1:是 0:否)', verbose_name='只有一个子路由是否始终显示'),
        ),
        migrations.AddField(
            model_name='menu',
            name='keep_alive',
            field=models.BooleanField(blank=True, default=False, help_text='【菜单】是否开启页面缓存(1:是 0:否)', verbose_name='是否开启页面缓存'),
        ),
    ]
