# Generated by Django 4.2.7 on 2023-12-06 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_menu_always_show_menu_keep_alive'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='roles',
            field=models.ManyToManyField(db_constraint=False, help_text='关联角色', related_name='menu_roles', to='users.role', verbose_name='关联角色'),
        ),
        migrations.AlterField(
            model_name='role',
            name='menu',
            field=models.ManyToManyField(db_constraint=False, help_text='关联菜单', related_name='role_menus', to='users.menu', verbose_name='关联菜单'),
        ),
    ]
